---
name: build
on: [push]
jobs:
  test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        distro: [ubuntu1604, ubuntu1804, ubuntu2004]
    steps:
      - name: Checkout with the directory name of actual Ansible Galaxy role name.
        uses: actions/checkout@v2
        with:
          path: tsukune_ch.canonical_livepatch
      - name: Setup python 3.x.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install test dependencies.
        run: >
          sudo pip install
          ansible-lint
          docker
          flake8
          'molecule>=3.0.2.1,<4.0'
          yamllint
      - name: Run tests.
        env:
          MOLECULE_DISTRO: ${{ matrix.distro }}
        run: |
          molecule test
